### ISSUE TITLE
would you release codes recently?

### ISSUE THREAD

**Issue by zherowolf** [google-research/lingvo-lab#1]
so that we can reproduce your excellent works. thx.

**Comment by chaiko** [comment]
Thanks for your interest in our work. Unfortunately, at the time being, we don't have plan to release the source code for Translatotron.

That said, we do include very comprehensive tables of hyperparameters in both the Translatotron 2 paper (https://arxiv.org/abs/2107.08661) and the Non-Attentive Tacotron paper (https://arxiv.org/abs/2010.04301), and many components used in Translatotron 2, such as Conformer, are already open sourced in the [Lingvo](https://github.com/tensorflow/lingvo) repository. Hope these can help you reproduce the results.
